# -*- coding: utf-8 -*-
"""N-Queen.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WbDrb1kDwGtaFlGgTngRntiOnVex3whX

Enter a value
"""

n=int(input("Enter a value:"))

"""Solves the problem by back-tracking method

"""

def solve_nqueens(i,ans):
  if i==n:
    solutions.append(ans[:])
    return
  for j in range(n):
    if is_safe(ans,i,j):
      ans.append(j)
      solve_nqueens(i+1,ans)
      ans.pop()

"""Checks if the placed queen is Safe or Not"""

def is_safe(ans,i,j):
  for k in range(i):
    if ans[k]==j or abs(ans[k]-j)==abs(k-i):
      return False
  return True

"""Displays the possible solutions"""

def display(solutions):
    print("The solutions are:")
    l=1
    for sol in solutions:
        print(f"Solution {l}:")
        l+=1
        for i in range(n):
            for j in range(n):
                if j == sol[i]:
                    print("Q", end=" ")
                else:
                    print(".", end=" ")
            print()
        print()

"""If there is no solutions prints no solution."""

solutions=[]
solve_nqueens(0,[])
if(solutions):
  display(solutions)
else:
  print("No solution")